PRFinance/PRFinance/Controllers/TransactionEditController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using PRFinance.Models;

namespace PRFinance.Controllers
{
    public class TransactionEditController : Controller
    {
        private TransactionDBContext db = new TransactionDBContext();

        // GET: /TransactionEdit/
        public ActionResult Index(CategoryEnum CategoryList = CategoryEnum.All)
        {
            var transactions = from m in db.Transactions 
                                              select m;

            var categoryList = new List<string>();
            foreach(var str in Enum.GetValues(typeof(CategoryEnum)))
            {
                categoryList.Add(((CategoryEnum)str).ToString());
            }
            ViewBag.CategoryList = new SelectList(categoryList);
            if (CategoryList != CategoryEnum.All)
            {

                transactions = transactions.Where(s => s.Category == CategoryList);
            }
            return View(transactions);
        }

        // GET: /TransactionEdit/
        public ActionResult Index2(CategoryEnum CategoryList = CategoryEnum.All)
        {
            var transactions = from m in db.Transactions
                               select m;

            var categoryList = new List<string>();
            foreach (var str in Enum.GetValues(typeof(CategoryEnum)))
            {
                categoryList.Add(((CategoryEnum)str).ToString());
            }
            ViewBag.CategoryList = new SelectList(categoryList);
            if (CategoryList != CategoryEnum.All)
            {

                transactions = transactions.Where(s => s.Category == CategoryList);
            }
            return View(transactions);
        }

        // GET: /TransactionEdit/
        public ActionResult Index3(CategoryEnum CategoryList = CategoryEnum.All)
        {
            var transactions = from m in db.Transactions
                               select m;

            var categoryList = new List<string>();
            foreach (var str in Enum.GetValues(typeof(CategoryEnum)))
            {
                categoryList.Add(((CategoryEnum)str).ToString());
            }
            ViewBag.CategoryList = new SelectList(categoryList);
            if (CategoryList != CategoryEnum.All)
            {

                transactions = transactions.Where(s => s.Category == CategoryList);
            }
            return View(transactions);
        }

        // GET: /TransactionEdit/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Transaction transaction = db.Transactions.Find(id);
            if (transaction == null)
            {
                return HttpNotFound();
            }
            return View(transaction);
        }

        // GET: /TransactionEdit/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: /TransactionEdit/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include="date,Category,Expense,Comment")] Transaction transaction)
        {
            if (ModelState.IsValid)
            {
                transaction.ID = DateTime.Now.ToString("yyyyMMddHHmmssfff");
                db.Transactions.Add(transaction);
                db.SaveChanges();
                return RedirectToAction("Index3");
            }

            return View(transaction);
        }

        // GET: /TransactionEdit/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Transaction transaction = db.Transactions.Find(id);
            if (transaction == null)
            {
                return HttpNotFound();
            }
            return View(transaction);
        }

        // POST: /TransactionEdit/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include="ID,date,Category,Expense,Comment")] Transaction transaction)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    db.Entry(transaction).State = EntityState.Modified;
                    db.SaveChanges();

                }
            }
            catch { }
            return RedirectToAction("Index3");
        }

        // GET: /TransactionEdit/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Transaction transaction = db.Transactions.Find(id);
            if (transaction == null)
            {
                return HttpNotFound();
            }
            return View(transaction);
        }

        // POST: /TransactionEdit/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            Transaction transaction = db.Transactions.Find(id);
            db.Transactions.Remove(transaction);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }


}

PRFinance/PRFinance/Views/TransactionEdit/Create.cshtml
@model PRFinance.Models.Transaction

@{
    ViewBag.Title = "Add transaction";
}

<h2>Add new transaction</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Transaction</h4>
        <hr />
        @Html.ValidationSummary(true)

        @*<div class="form-group">
            @Html.LabelFor(model => model.ID, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ID)
                @Html.ValidationMessageFor(model => model.ID)
            </div>
        </div>*@

        <div class="form-group">
            @Html.LabelFor(model => model.date, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.date)
                @Html.ValidationMessageFor(model => model.date)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Category, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Category)
                @Html.ValidationMessageFor(model => model.Category)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Expense, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Expense)
                @Html.ValidationMessageFor(model => model.Expense)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Comment, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Comment)
                @Html.ValidationMessageFor(model => model.Comment)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

PRFinance/PRFinance/Views/TransactionEdit/Delete.cshtml
@model PRFinance.Models.Transaction

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Transaction</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.date)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.date)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Category)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Category)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Expense)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Expense)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Comment)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Comment)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

PRFinance/PRFinance/Views/TransactionEdit/Details.cshtml
@model PRFinance.Models.Transaction

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Transaction</h4>
	<hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.date)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.date)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Category)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Category)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Expense)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Expense)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Comment)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Comment)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

PRFinance/PRFinance/Views/TransactionEdit/Edit.cshtml
@model PRFinance.Models.Transaction

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Transaction</h4>
        <hr />
        @Html.ValidationSummary(true)
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.date, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.date)
                @Html.ValidationMessageFor(model => model.date)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Category, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Category)
                @Html.ValidationMessageFor(model => model.Category)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Expense, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Expense)
                @Html.ValidationMessageFor(model => model.Expense)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Comment, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Comment)
                @Html.ValidationMessageFor(model => model.Comment)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index", null, new { @class = "Nav"})
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

PRFinance/PRFinance/Views/TransactionEdit/Index2.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}


@model IEnumerable<PRFinance.Models.Transaction>

@{
    ViewBag.Title = "Index";
}

<h2>Transactions</h2>

<p>
    @Html.ActionLink("Create New", "Create")

    @using (Html.BeginForm())
    {
    <p>
        Category: @Html.DropDownList("CategoryList", "All")
        &nbsp
        <input type="submit" value="Filter" />
    </p>
    }
    </p>


    @*<table class="table">
       
        <thead style="display:table-header-group;">
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.date)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Category)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Expense)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Comment)
                </th>

            </tr>
        </thead>

        <tbody data-bind="template: { name: templateToUse, foreach: items}"></tbody>


    </table>*@


<script id="itemTmpl" type="text/html">
    <tr>
        <td data-bind="text: model.date"></td>
        <td data-bind="text: model.Category"></td>
        <td data-bind="text: model.Expense"></td>
        <td data-bind="text: model.Comment"></td>
        <td class="buttons">
            <button data-bind="click: $root.editItem">Edit</button>
            <button data-bind="click: $root.deleteItem">Delete</button>

        </td>
    </tr>
</script>

<script id="editTmpl" type="text/html">
    <tr>
        <td>
            <input data-bind="value: date" />
        </td>
        <td>
            <input data-bind="value: Category" />
        </td>
        <td>
            <input data-bind="value: Expense" />
        </td>
        <td>
            <input data-bind="value: Comment" />
        </td>
        <td class="buttons">
            <button data-bind="click: $root.acceptItemEdit">Accept</button>
            <button data-bind="click: $root.cancelItemEdit">Cancel</button>
        </td>
    </tr>
</script>
    

    <tr class="zebra">
            <td colspan="4">
                <table class="table-striped">
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.date)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Category)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Expense)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Comment)
                        </td>
                        <td>

                            <input id=@iid type="submit" value="Edit" onclick="return EditClick('@iid');" /> |
                            @Html.ActionLink("Details", "Details", new { id = item.ID }, new { @class = "Edit" }) |
                            @Html.ActionLink("Delete", "Delete", new { id = item.ID }, new { @class = "Delete" })
                        </td>
                    </tr>



                    <tr id=@name style="display:none">
                        <td>
                            <div>
                                <h4 style="color:gray">Transaction Details</h4>
                                <hr />
                                <dl class="dl-horizontal">
                                    <dt>
                                        @Html.DisplayNameFor(model => model.date)
                                    </dt>

                                    <dd>
                                        @Html.DisplayFor(modelItem => item.date)
                                    </dd>

                                    <dt>
                                        @Html.DisplayNameFor(model => model.Category)
                                    </dt>

                                    <dd>
                                        @Html.DisplayFor(modelItem => item.Category)
                                    </dd>

                                    <dt>
                                        @Html.DisplayNameFor(model => model.Expense)
                                    </dt>

                                    <dd>
                                        @Html.DisplayFor(modelItem => item.Expense)
                                    </dd>

                                    <dt>
                                        @Html.DisplayNameFor(model => model.Comment)
                                    </dt>

                                    <dd>
                                        @Html.DisplayFor(modelItem => item.Comment)
                                    </dd>

                                </dl>
                            </div>
                        </td>
                    </tr>
                </table>
            </td>

        </tr>

PRFinance/PRFinance/Views/TransactionEdit/Index3.cshtml
@model IEnumerable<PRFinance.Models.Transaction>

@{
    ViewBag.Title = "Index";
}

<h2>Transactions</h2>

<br />
<!-- Create section -->
<section style="background-color: #D8E4E8">

    <input id="CreateButton" type="button" class="btn btn-default" value="Create New" onclick="return CreateClick();" />

    <div class="col-md-12" style=" display:none" id="CreatePane">
        @using (Html.BeginForm("Create", "TransactionEdit", FormMethod.Post, new { @class = "TransactionForm" }))
        {

            @Html.AntiForgeryToken()

            <div class="form-horizontal">
                <h4>Transaction</h4>
                <hr />
                @Html.ValidationSummary(true)

                <fieldset>

                    <div class="form-group">
                        <div class="col-md-4">
                            @Html.DisplayNameFor(model => model.date)
                        </div>
                        <div class="col-md-8">
                            @Html.TextBox("CreateDate")
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-md-4">
                            @Html.DisplayNameFor(model => model.Category)
                        </div>
                        <div class="col-md-8">
                            @Html.DropDownList("CategoryList", "All")
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-md-4">
                            @Html.DisplayNameFor(model => model.Expense)
                        </div>
                        <div class="col-md-8">
                            @Html.TextBox("Expense")
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-md-4">
                            @Html.DisplayNameFor(model => model.Comment)
                        </div>
                        <div class="col-md-8">
                            @Html.TextBox("Comment")
                        </div>
                    </div>

                    <div class="form-group">
                        <div style="float:left">
                            <input type="submit" value="Save" class="btn btn-default" />
                        </div>
                        <div style="float:left">
                            <input id="CreateCancel" type="button" value="Cancel" class="Delete" onclick="return CancelCreate();" />
                        </div>
                    </div>
                </fieldset>
            </div>

        }
    </div>
</section>

<div style="height:5px; fill:blue"></div>
<!-- Filter -->   
    @using (Html.BeginForm())
    {
        <p>
        Category: @Html.DropDownList("CategoryList", "All")
        &nbsp
        <input type="submit" value="Filter" />
        </p>
    }

<!-- Table headers-->
<div class="SingleElement" style="display:table-header-group" >
    @Html.DisplayNameFor(model => model.date)
</div>
<div class="SingleElement">
    @Html.DisplayNameFor(model => model.Category)
</div>
<div class="SingleElement">
    @Html.DisplayNameFor(model => model.Expense)
</div>
<div class="SingleElement">
    @Html.DisplayNameFor(model => model.Comment)
</div>
    
<br />

<!-- Data list -->
@foreach (var item in Model)
{
    string iid = item.ID;
    string name = "DetailPane" + item.ID;
    string eName = "EditPane" + item.ID;
    string dbutton = "D" + iid;
    string ebutton = "E" + iid;
    <p>
        <div class="block" onmouseover="return ContentMouseOver('@iid')">
            <div class="SingleElement">
                @Html.DisplayFor(modelItem => item.date)
            </div>
            <div class="SingleElement">
                @Html.DisplayFor(modelItem => item.Category)
            </div>
            <div class="SingleElement">
                @Html.DisplayFor(modelItem => item.Expense)
            </div>
            <div class="SingleElement">
                @Html.DisplayFor(modelItem => item.Comment)
            </div>
            <div class="MultiElement">
                <input id=@dbutton type="submit" value="Details"  onclick="return DetailClick('@iid');" /> |
                <input id=@ebutton type="submit" value="Edit"  onclick="return EditClick('@iid');" /> |
                @Html.ActionLink("Delete", "Delete", new { id = item.ID }, new { @class = "Delete" })
            </div>
        </div>
        <div style="width=100%; display:none" id="@name">
            <h4 style="color:gray">Transaction Details</h4>
            <hr />
            <dl class="dl-horizontal">
                <dt>
                    @Html.DisplayNameFor(model => model.date)
                </dt>

                <dd>
                    @Html.DisplayFor(modelItem => item.date)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Category)
                </dt>

                <dd>
                    @Html.DisplayFor(modelItem => item.Category)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Expense)
                </dt>

                <dd>
                    @Html.DisplayFor(modelItem => item.Expense)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Comment)
                </dt>

                <dd>
                    @Html.DisplayFor(modelItem => item.Comment)
                </dd>

            </dl>
        </div>
        
            @using (Html.BeginForm("Edit", "TransactionEdit", new { ID = item.ID, date = item.date, Category = item.Category, Expense = item.Expense, Comment = item.Comment }, FormMethod.Post, new { @class = "TransactionForm" }))
{
    <div style="width:100%; display:none" id="@eName">
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <h4>Transaction</h4>
            <hr />
            @Html.ValidationSummary(true)

            <fieldset>
                @Html.HiddenFor(model => item.ID)

                <div class="form-group">
                    @Html.LabelFor(modelItem => item.date, new { @class = "control-label col-md-4" })
                    <div class="col-md-8">
                        @Html.EditorFor(modelItem => item.date, "", "date")
                        @Html.ValidationMessageFor(modelItem => item.date)
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(modelItem => item.Category, new { @class = "control-label col-md-4" })
                    <div class="col-md-8">
                        @Html.EditorFor(modelItem => item.Category, "", "Category")
                        @Html.ValidationMessageFor(modelItem => item.Category)
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(modelItem => item.Expense, new { @class = "control-label col-md-4" })
                    <div class="col-md-8">
                        @Html.EditorFor(modelItem => item.Expense, "", "Expense")
                        @Html.ValidationMessageFor(modelItem => item.Expense)
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(modelItem => item.Comment, new { @class = "control-label col-md-4" })
                    <div class="col-md-8">
                        @Html.EditorFor(modelItem => item.Comment, "", "Comment")
                        @Html.ValidationMessageFor(modelItem => item.Comment)
                    </div>
                </div>

                <div class="form-group">
                    <div style="float:left">
                        <input type="submit" value="Save" class="btn btn-default" />
                    </div>
                </div>
            </fieldset>

        </div>
    </div>
}
        
</p>
    <br />
}
                

    <script>

        $(document).ready(function () {
            $("#CreateDate").datepicker({ dateFormat: 'dd/mm/yy' });
        });

        function EditClick(sid) {
            if (document.getElementById("EditPane" + sid).style.display == "none") {
                document.getElementById("DetailPane" + sid).style.display = "none"
                document.getElementById("EditPane" + sid).style.display = "table-row"
            }
            else {
                document.getElementById("EditPane" + sid).style.display = "none"
            }

            if (document.getElementById("CreatePane").style.display != "none")
            {
                CreateCancel();
            }
        }

        function CreateClick() {
            if (document.getElementById("CreatePane").style.display == "none") {
                
                document.getElementById("CreatePane").style.display = "table-row"
                document.getElementById("CreateButton").style.display = "none"
            }
            else {
                document.getElementById("CreatePane" ).style.display = "none"
            }
        }

        function CancelCreate() {
            document.getElementById("CreatePane").style.display = "none";
            document.getElementById("CreateButton").style.display = "table-row";
        }

        function ContentMouseOver(sid)
        {
            document.getElementById("D" + sid).style.display == "none"
            document.getElementById("E" + sid).style.display == "table-row"
            document.getElementById("CreatePane").style.display = "table-row"
            document.getElementById("CreateButton").innerHTML = "<div>" + sid + "</div>"
        }
        function DetailClick(sid) {
            if (document.getElementById("DetailPane" + sid).style.display == "none") {
                document.getElementById("DetailPane" + sid).style.display = "table-row"
                document.getElementById("EditPane" + sid).style.display = "none"
            }
            else {
                document.getElementById("DetailPane" + sid).style.display = "none"
            }

            $(document).ready(function () {
                $('.edit')
            });
        }
    </script>

    @*<tr class="zebra">
            <td colspan="4">
                <table class="table-striped">
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.date)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Category)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Expense)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Comment)
                        </td>
                        <td>

                            <input id=@iid type="submit" value="Edit" onclick="return EditClick('@iid');" /> |
                            @Html.ActionLink("Details", "Details", new { id = item.ID }, new { @class = "Edit" }) |
                            @Html.ActionLink("Delete", "Delete", new { id = item.ID }, new { @class = "Delete" })
                        </td>
                    </tr>



                    <tr id=@name style="display:none">
                        <td>
                            <div>
                                <h4 style="color:gray">Transaction Details</h4>
                                <hr />
                                <dl class="dl-horizontal">
                                    <dt>
                                        @Html.DisplayNameFor(model => model.date)
                                    </dt>

                                    <dd>
                                        @Html.DisplayFor(modelItem => item.date)
                                    </dd>

                                    <dt>
                                        @Html.DisplayNameFor(model => model.Category)
                                    </dt>

                                    <dd>
                                        @Html.DisplayFor(modelItem => item.Category)
                                    </dd>

                                    <dt>
                                        @Html.DisplayNameFor(model => model.Expense)
                                    </dt>

                                    <dd>
                                        @Html.DisplayFor(modelItem => item.Expense)
                                    </dd>

                                    <dt>
                                        @Html.DisplayNameFor(model => model.Comment)
                                    </dt>

                                    <dd>
                                        @Html.DisplayFor(modelItem => item.Comment)
                                    </dd>

                                </dl>
                            </div>
                        </td>
                    </tr>
                </table>
            </td>

        </tr>*@